apiVersion: v1
kind: Secret
metadata:
  name: marketing-project-secrets
  namespace: marketing-project
  labels:
    app: marketing-project-api
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret" | base64
  API_KEY: "cHJvZC1hcGkta2V5LTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEy"
  API_KEY_1: "YWRtaW4ta2V5LTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEy"
  API_KEY_1_ROLE: "YWRtaW4="
  API_KEY_2: "dXNlci1rZXktMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="
  API_KEY_2_ROLE: "dXNlcg=="
  
  # OpenAI API Key
  OPENAI_API_KEY: "eW91ci1vcGVuYWktYXBpLWtleS1iYXNlNjQtZW5jb2RlZA=="
  
  # Database passwords
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="
  MONGODB_PASSWORD: "cGFzc3dvcmQ="
  REDIS_PASSWORD: ""
  
  # Additional marketing project secrets
  CONTENT_API_KEY: "eW91ci1jb250ZW50LWFwaS1rZXktYmFzZTY0LWVuY29kZWQ="
  ANALYTICS_TOKEN: "eW91ci1hbmFseXRpY3MtdG9rZW4tYmFzZTY0LWVuY29kZWQ="
  WEBHOOK_SECRET: "eW91ci13ZWJob29rLXNlY3JldC1iYXNlNjQtZW5jb2RlZA=="
