apiVersion: v1
kind: Secret
metadata:
  name: marketing-project-secrets
  namespace: marketing-project
type: Opaque
data:
  # Base64 encoded API keys
  API_KEY: cHJvZC1hcGkta2V5LTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEy
  API_KEY_1: YWRtaW4ta2V5LTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEy
  API_KEY_1_ROLE: YWRtaW4=
  API_KEY_2: dXNlci1rZXktMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
  API_KEY_2_ROLE: dXNlcg==
  # Database passwords
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  MONGODB_PASSWORD: cGFzc3dvcmQ=
  REDIS_PASSWORD: ""
