apiVersion: v1
kind: Secret
metadata:
  name: marketing-project-secrets
  namespace: marketing-project
  labels:
    app: marketing-project-api
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret" | base64
  
  # OpenAI API Key (if needed for AI functionality)
  OPENAI_API_KEY: "eW91ci1vcGVuYWktYXBpLWtleS1iYXNlNjQtZW5jb2RlZA=="
  
  # Content API Key (if using external content APIs)
  CONTENT_API_KEY: "eW91ci1jb250ZW50LWFwaS1rZXktYmFzZTY0LWVuY29kZWQ="