name: Dependency Matrix

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  dependency-matrix:
    name: Dependencies ${{ matrix.deps }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deps: ['minimal', 'latest', 'pinned']
        include:
          - deps: 'minimal'
            requirements: 'requirements-minimal.txt'
          - deps: 'latest'
            requirements: 'requirements-latest.txt'
          - deps: 'pinned'
            requirements: 'requirements.txt'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install minimal dependencies
      if: matrix.deps == 'minimal'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install -e .
        
    - name: Install latest dependencies
      if: matrix.deps == 'latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade -r requirements.txt
        pip install -e .
        
    - name: Install pinned dependencies
      if: matrix.deps == 'pinned'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        
    - name: Run tests
      run: |
        pytest tests/ -v --maxfail=3
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Test CLI
      run: |
        marketing-project --help
        marketing-project run --help
        marketing-project serve --help
