name: Performance Tests

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements*.txt'
  workflow_dispatch:

jobs:
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install pytest-benchmark memory-profiler
        pip install -e .
        
    - name: Run performance tests
      run: |
        pytest tests/ -v --benchmark-only --benchmark-sort=mean
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        API_KEY: test-key-12345678901234567890123456789012
        
    - name: Memory usage test
      run: |
        python -m memory_profiler -c "
        from src.marketing_project.runner import run_marketing_project_pipeline
        print('Memory test completed')
        "
        
    - name: Security performance test
      run: |
        python test_security_and_database.py
      env:
        API_KEY: test-key-12345678901234567890123456789012
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  load-test:
    name: Load Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust
        pip install -e .
        
    - name: Start server in background
      run: |
        python -m uvicorn src.marketing_project.server:app --host 0.0.0.0 --port 8000 &
        sleep 10
      env:
        API_KEY: test-key-12345678901234567890123456789012
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Run comprehensive load test
      run: |
        python run_load_test.py --url http://localhost:8000 --test all --output comprehensive_load_test.json
      env:
        API_KEY: test-key-12345678901234567890123456789012
        
    - name: Upload load test results
      uses: actions/upload-artifact@v4
      with:
        name: load-test-results
        path: comprehensive_load_test.json
